<style>
    /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
    #map {
        height: 100%;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }
    .controls {
        background-color: #fff;
        border-radius: 2px;
        border: 1px solid transparent;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        box-sizing: border-box;
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
        height: 29px;
        margin-left: 17px;
        margin-top: 10px;
        outline: none;
        padding: 0 11px 0 13px;
        text-overflow: ellipsis;
        width: 400px;
    }

    .controls:focus {
        border-color: #4d90fe;
    }
    .title {
        font-weight: bold;
    }
    #infowindow-content {
        display: none;
    }
    #map #infowindow-content {
        display: inline;
    }
</style>
<!--CONTENIDO-->
<div class="be-left-sidebar">
    <div class="left-sidebar-wrapper">
        <div class="left-sidebar-spacer">
            <div class="left-sidebar-scroll">
                <div class="left-sidebar-content">
                    <ul class="sidebar-elements">

                        <div class="panel-group" role="tablist">
                            <div class="panel panel-default">


                                <div class="panel-heading" role="tab" id="collapseListGroupHeading-1">
                                    <a href="#collapseListGroup-1" role="button" data-toggle="collapse" aria-expanded="true" aria-controls="collapseListGroup-1"> <i class="icon mdi mdi-layers"></i><span> Test </span> </a>
                                </div>
                                <div class="panel-collapse collapse in" role="tabpanel" id="collapseListGroup-1" aria-labelledby="collapseListGroupHeading-1" aria-expanded="true">
                                    <ul class="list-group">
                                        <li class="list-group-item"><a class="loadPantalla" href="<?php echo $this->baseUrl; ?>/controlactivos/index/view-usuario" data-mod="1" data-cont="1" data-acc="1" role="button"> Usuario </a> </li>
                                        <li class="list-group-item"><a class="loadPantalla" href="<?php echo $this->baseUrl; ?>/controlactivos/index/view-construc" data-mod="1" data-cont="1" data-acc="1" role="button"> Construcción </a> </li>
                                        <li class="list-group-item"><a class="loadPantalla" href="<?php echo $this->baseUrl; ?>/controlactivos/index/view-map" data-mod="1" data-cont="1" data-acc="1" role="button"> Maps </a> </li>
                                        <li class="list-group-item"><a class="loadPantalla" href="<?php echo $this->baseUrl; ?>/controlactivos/index/view-login" data-mod="1" data-cont="1" data-acc="1" role="button"> Salir </a> </li>
                                    </ul>
                                </div>

                            </div>
                        </div>

                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="be-content">
    <div class="card card-table">
        <div class="card-header">Catálogo construcción
            <div class="tools">
                <button id="btnRegistrar" name="btnRegistrar" class="btn btn-space btn-info"><i class="icon mdi mdi-collection-plus"></i> Registrar Construcción </button>
            </div>
        </div>
        <div class="card-header-divider"></div>
        <div class="card-body">
            <span class="msjRespuesta"> </span>
            <!-- Inicio de tabla -->
            <table id="dt_proveedor" class="display">
                <thead>
                <tr>
                    <th>CÓDIGO</th>
                    <th>CLAVE</th>
                    <th>NOMBRE</th>
                    <th>USUARIO</th>
                    <th>ACCIÓN</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
            <!-- FIN  Inicio de tabla -->
        </div>
    </div>
</div>

    <!--MODAL-->
    <div id="form-bp1" tabindex="-1" role="dialog" class="modal fade colored-header colored-header-success"
         aria-hidden="true">
        <div class="modal-dialog">
            <form id="formConstruccion" name="formConstruccion">
                <!-- Campos hidden -->
                <input id="inptProceso" name="inptProceso" type="hidden" value="Guardar"/>
                <input id="inpId" name="inpId" type="hidden" />

                <div class="modal-content">
                    <div class="modal-header modal-header-colored">
                        <h3 id="bntTitulomodal" class="modal-title"> <i id="icoTitulo" class="icon mdi mdi-collection-plus"></i>  <span id="spTitulomodalRegEdit">Registrar</span>  Construcción</h3>
                        <button name="btnCerrarX" type="button" data-dismiss="modal" aria-hidden="true" class="close md-close"><span
                                class="mdi mdi-close"> </span></button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label><h5><span class="glyphicon-red"> ( * )</span> Nombre:</h5></label>
                            <input id="inpNombre" name="inpNombre" type="text" placeholder="Ingrese nombre connstrucción" class="form-control soloLetras" value="prueba">
                            <!-- Componente msj-->
                            <div class="error" style="display:none"> <b class="border-notch notch"></b>
                            </div>
                            <!-- Componente msj-->
                        </div>

                        <div class="form-group">
                            <label><h5><span class="glyphicon-red"> ( * )</span> Clave:</h5></label>
                            <input id="inpClave" name="inpClave" type="text" maxlength="20" placeholder="Ingrese clave valida" class="form-control soloLetrasNumCar valExpresion">
                            <!-- Componente msj-->
                            <div id="valMsjExpresion" class="error" > <b class="border-notch notch"></b>
                            </div>
                            <!-- Componente msj-->
                        </div>

                        <div class="form-group">
                            <label><h5><span class="glyphicon-red"> ( * )</span>  Descripción :</h5></label>
                            <textarea id="inpDes" name="inpDes" placeholder="Ingrese una descripción" class="form-control soloLetrasNum" cols="3" rows="3" >prueba</textarea>
                            <!-- Componente msj-->
                            <div class="error" style="display:none"> <b class="border-notch notch"></b>
                            </div>
                            <!-- Componente msj-->
                        </div>

                        <div class="form-group">
                            <label><h5><span class="glyphicon-red"> ( * )</span> Delegación:</h5></label>
                            <input id="inpDelegacion" name="inpDelegacion" type="text" maxlength="20" placeholder="Ingrese delegación" class="form-control soloLetrasNum" value="prueba">
                            <!-- Componente msj-->
                            <div class="error" style="display:none"> <b class="border-notch notch"></b>
                            </div>
                            <!-- Componente msj-->
                        </div>

                        <div class="form-group">
                            <label><h5><span class="glyphicon-red"> ( * )</span> Colonía:</h5></label>
                            <input id="inpColonia" name="inpColonia" type="text" maxlength="20" placeholder="Ingrese colonia" class="form-control soloLetrasNum"  value="prueba">
                            <!-- Componente msj-->
                            <div class="error" style="display:none"> <b class="border-notch notch"></b>
                            </div>
                            <!-- Componente msj-->
                        </div>

                        <div class="form-group">
                            <label><h5><span class="glyphicon-red"> ( * )</span> Calle:</h5></label>
                            <input id="inpCalle" name="inpCalle" type="text" maxlength="20" placeholder="Ingrese calle" class="form-control soloLetrasNum"  value="prueba">
                            <!-- Componente msj-->
                            <div class="error" style="display:none"> <b class="border-notch notch"></b>
                            </div>
                            <!-- Componente msj-->
                        </div>

                        <div class="form-group">
                            <label><h5><span class="glyphicon-red"> ( * )</span> Latitud:</h5></label>
                            <input id="inpLat" name="inpLat" type="text" maxlength="30" placeholder="Ingrese latitud" class="form-control "  value="prueba">
                            <!-- Componente msj-->
                            <div class="error" style="display:none"> <b class="border-notch notch"></b>
                            </div>
                            <!-- Componente msj-->
                        </div>

                        <div class="form-group">
                            <label><h5><span class="glyphicon-red"> ( * )</span> Longitud :</h5></label>
                            <input id="inpLog" name="inpLog" type="text" maxlength="30" placeholder="Ingrese longitud" class="form-control "  value="prueba" >
                            <!-- Componente msj-->
                            <div class="error" style="display:none"> <b class="border-notch notch"></b>
                            </div>
                            <!-- Componente msj-->
                        </div>


                        <input id="pac-input" class="controls" type="text" placeholder="Ingrese posible dirección">
                        <div id="map"  style="width: 90%; height: 30%;position: absolute" ></div>
                        <div id="infowindow-content">
                            <span id="place-name"  class="title"></span><br>
                            Place ID <span id="place-id"></span><br>
                            <span id="place-address"></span>
                        </div>


                        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>


                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="custom-control">
                                    ( * )  <span class="custom-control-label">Los campos con asterisco son obligatorios.</span>
                                </label>
                            </div>
                        </div>


                        <div class="row">
                            <div class="form-group col-md-12">
                                <label  class="custom-control msjRespuesta">  </label>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button id="btnCerrar" name="btnCerrar" type="button" data-dismiss="modal" class="btn btn-default md-close">Cerrar</button>
                        <button id="btnGuardar" name="btnGuardar" type="submit" class="btn btn-success"> <span id="sTituloBoton"> Registar </span>   </button>
                    </div>
                </div>
            </form>
        </div>
    </div>



<script>
        function initMap() {
            var map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: 19.4978, lng: -99.1269},
                zoom: 13
            });

            var input = document.getElementById('pac-input');
            console.log(input);

            var autocomplete = new google.maps.places.Autocomplete(input);
            autocomplete.bindTo('bounds', map);

            map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

            var infowindow = new google.maps.InfoWindow();
            var infowindowContent = document.getElementById('infowindow-content');
            infowindow.setContent(infowindowContent);

            var marker = new google.maps.Marker({
                map: map
            });
            marker.addListener('click', function() {
                infowindow.open(map, marker);
            });

            autocomplete.addListener('place_changed', function() {
                infowindow.close();

                var place = autocomplete.getPlace();
                if (!place.geometry) {
                    return;
                }

                if (place.geometry.viewport) {
                    map.fitBounds(place.geometry.viewport);
                } else {
                    map.setCenter(place.geometry.location);
                    map.setZoom(17);
                }

                // Set the position of the marker using the place ID and location.
                marker.setPlace({
                    placeId: place.place_id,
                    location: place.geometry.location
                });

                marker.setVisible(true);

                infowindowContent.children['place-name'].textContent = place.name;
                infowindowContent.children['place-id'].textContent = place.place_id;
                infowindowContent.children['place-address'].textContent =  place.formatted_address;

                infowindow.open(map, marker);
            });
        }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA4UyBLPV2Op1BNg31pMhHI8UfNne6e6n8&libraries=places&callback=initMap" async defer></script>
<script type="text/javascript" src="<?php echo $this->baseUrl; ?>/js/activo/view-construc.js"></script>



