<style>
    /* Always set the map height explicitly to define the size of the div
     * element that contains the map. */
    #map {
        height: 100%;
    }

    #siteNotice {
        height: 50px !important;
        widtht: 70px !important;
    }
    /* Optional: Makes the sample page fill the window. */
    html, body {
        height: 100%;
        margin: 0;
        padding: 0;
    }
</style>

<div id="map"></div>
<script>
    var customLabel = {
        restaurant: {
            label: 'R'
        },
        bar: {
            label: 'B'
        }
    };

    // Note: This example requires that you consent to location sharing when
    // prompted by your browser. If you see the error "The Geolocation service
    // failed.", it means you probably did not give permission for the browser to
    // locate you.
    var map, infoWindow;

    var locations = '<?=$this->COOR_CONSTRUC?>';
    locations = $.parseJSON(locations);
    var  ruta = '<?php echo $this->baseUrl; ?>';


    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 19.4978, lng: -99.1269},
            zoom: 12,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        /*AQUI MARKER QUE INDICA COORDENADAS CUANDO SE ARASTRA */

        marker = new google.maps.Marker({
            map: map,
            draggable: true,
            animation: google.maps.Animation.DROP,
            position: {lat: 19.4978, lng: -99.1269},
            icon: ruta + '/images/icoMap/radar.png',
            title: 'Buscar tus Coordenadas',
        });

        infoWindow2 = new google.maps.InfoWindow;
        var pos2 = {
            lat: 19.4978,
            lng: -99.1269
        };

        infoWindow2.setPosition(pos2);
        infoWindow2.setContent('Arrastra y clic sobre el icono para saber  coordenadas,<br> refrescar solo cierra y vuelve arrastrar');
        infoWindow2.open(map);



        google.maps.event.addListener(marker, 'click', function(){
            openInfoWindow(marker);
            toggleBounce();
        });

        /*AQUI MARKER QUE INDICA COORDENADAS CUANDO SE ARASTRA */

        /*AQUI DECLARO MARKER MULTIPLES */
        var marker2, i;
        var infowindow = new google.maps.InfoWindow();

        for (i = 0; i < locations.length; i++) {
            marker2 = new google.maps.Marker({
                position: new google.maps.LatLng(locations[i][4], locations[i][5]),
                icon: ruta + '/images/icoMap/'+locations[i][6],
                map: map
            });


            var contentStringMultiple = '<div id="content">'+
                '<h3 id="firstHeading" class="firstHeading">'+ locations[i][1] + '</h3>'+
                '<div id="bodyContent">'+
                '<p><b>Clave: '+ locations[i][1] + '</b>  </p>' +
                '<p><b>Latitud:</b>  '+ locations[i][4] + '</p>'+
                '<p><b>Longitud:</b>  '+ locations[i][5] + '</p>'+
                '<p><b>Dirección:</b> '+ locations[i][3] + '</p>'+
                '<p><b>Url:</b>  <a href="#">Url</a> '+ '</p>'+
                '</div>'+
                '</div>';

            google.maps.event.addListener(marker2, 'click', (function(marker, i) {
                return function() {
                    infowindow.setContent(contentStringMultiple);
                    infowindow.open(map, marker2);
                }
            })(marker, i));

        }

        /*AQUI DECLARO MARKER MULTIPLES */



        // Try HTML5 geolocation.

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                //coordenadas actuales
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                /*AQUI MARKER QUE INDICA COORDENADAS DE TU POSICION ACTUAL */

                marker3 = new google.maps.Marker({
                    map: map,
                    draggable: false,
                    animation: google.maps.Animation.DROP,
                    position: {lat: position.coords.latitude, lng: position.coords.longitude},
                    icon: ruta + '/images/icoMap/sonreir.png',
                    title: 'Aqui estas TU...',
                });

                google.maps.event.addListener(marker3, 'click', function(){
                    openInfoWindow(marker3);
                    //toggleBounce();
                });

                /*AQUI MARKER QUE INDICA COORDENADAS DE TU POSICION ACTUAL */

                infoWindow = new google.maps.InfoWindow;
                infoWindow.setPosition(pos);
                infoWindow.setContent('Tu estas aproximadamente Aquí.');
                infoWindow.open(map);
                //map.setCenter(pos);

            }, function() {
                handleLocationError(true, infoWindow, map.getCenter());
            });
        } else {
            // Browser doesn't support Geolocation
            handleLocationError(false, infoWindow, map.getCenter());
        }

    }





    function toggleBounce() {
        if (marker.getAnimation() !== null) {
            marker.setAnimation(null);
        } else {
            marker.setAnimation(google.maps.Animation.BOUNCE);
        }
    }

    function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
            'El servicio de geo ha fallado' :
            'Error: Tu navegador no soporta geolocalización.');
        infoWindow.open(map);
    }

    function openInfoWindow(marker) {
        var markerLatLng = marker.getPosition();
        var direccion ='Avenida';
        var contentString = '<div id="content">'+
            '<h3 id="firstHeading" class="firstHeading">Tus Coordenadas</h3>'+
            '<div id="bodyContent">'+
            '<p><b>Refrescar, solo cierra la ventana</b>  </p>' +
            '<p>Latitud:  '+ markerLatLng.lat() + '</p>'+
            '<p>Longitud:  '+ markerLatLng.lng() + '</p>'+
            '<p>Url:  <a href="#">Url</a> '+ '</p>'+
            '</div>'+
            '</div>';

        var infoWindow = new google.maps.InfoWindow({
            content: contentString
        });

        infoWindow.open(map, marker);
    }

    function downloadUrl(url, callback) {
        var request = window.ActiveXObject ?
            new ActiveXObject('Microsoft.XMLHTTP') :
            new XMLHttpRequest;

        request.onreadystatechange = function() {
            if (request.readyState == 4) {
                request.onreadystatechange = doNothing;
                callback(request, request.status);
            }
        };

        request.open('GET', url, true);
        request.send(null);
    }

    function doNothing() {}

</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA4UyBLPV2Op1BNg31pMhHI8UfNne6e6n8&callback=initMap">
</script>